#!/usr/bin/python -w

import os 
import pickle

def main():
	if not os.path.exists(r'/root/contact.data'):
		f = open('/root/contact.data','wb')
		temp = {'total':0}
		pickle.dump(temp,f)
		f.close()
	point()
	while True:
		_input = raw_input('Please input your choose:')
		if _input == '*':
			point()
			continue
		elif _input == '1':
			showall()
			continue
		elif _input == '2':
			add()
			continue
		elif _input == '3':
			delete()
			continue
		elif _input == '4':
			find()
			continue
		elif _input == '5':
			change()
			continue
		elif _input == '6':
			quit()
		else:
			print "input isn't exists,Please input again"	

def point():
	print "Show Toolkip: *"
	print "Show all contact: 1"
	print "Add contact: 2"
	print "Delete contact: 3"
	print "Find contact: 4"
	print "Change contact: 5"
	print "Quit contact: 6"

def showall():
	f = open('/root/contact.data','rb')
	info = pickle.load(f)
	print "How many contact is %s" % info['total']
	for key in info:
		if key != total:
			print "%s : %s" % (key , info(key))
	

def add():
	pass

def delete():
	pass

def change():
	pass

def find():
	pass

def quit():
	exit()

if __name__ == '__main__':
	main()
