#!/usr/bin/python -w

import os 
import pickle

def main():
	if not os.path.exists(r'/root/contact.data'):
		f = open('/root/contact.data','rb')
		temp = {total:0}
		pickle.dump(temp,f)
		f.close()
	point()
	

def point():
	print "Show Toolkip: *"
	print "Show all contact: 1"
	print "Add contact: 2"
	print "Delete contact: 3"
	print "Find contact: 4"
	print "Change contact: 5"
	print "Quit contact: 6"

def showall():
	pass

def add():
	pass

def delete():
	pass

def change():
	pass

def find():
	pass

def quit():
	exit()
if __name__ == '__main__':
	main()
